/**
 * Warden Trust Propagation & QUARANTINE Example
 *
 * Demonstrates TrustRegistry — track value trust across multiple tool calls.
 * When EXTERNAL content flows into a write operation, QUARANTINE strips it
 * before allowing the sanitized call through.
 *
 * Run: npx tsx examples/trust-quarantine/index.ts
 */

import {
  evaluate,
  tagValue,
  TrustLevel,
  TrustRegistry,
  sanitizeExternalValues,
  MemoryLedgerStore,
} from "@stlw/warden";
import type { PolicyConfig } from "@stlw/warden";

// Policy with QUARANTINE rule: EXTERNAL content cannot flow into write_file
const config: PolicyConfig = {
  version: "2",
  meta: { environment: "development", sessionApprovalRequired: false },
  policies: [
    {
      id: "allow-reads",
      description: "Allow read operations in dev",
      match: {
        tools: ["read_file", "list_directory", "Bash"],
        trustSource: [TrustLevel.SYSTEM, TrustLevel.AGENT, TrustLevel.TOOL, TrustLevel.EXTERNAL],
        environment: ["development"],
      },
      action: "ALLOW",
    },
    {
      id: "quarantine-external-to-write",
      description: "External content must be stripped before writes",
      match: {
        trustSource: [TrustLevel.EXTERNAL],
        nextTool: ["write_file", "send_email"],
      },
      action: "QUARANTINE",
    },
    {
      id: "allow-trusted-writes",
      description: "Allow writes with non-EXTERNAL trust",
      match: {
        tools: ["write_file"],
        trustSource: [TrustLevel.SYSTEM, TrustLevel.AGENT, TrustLevel.TOOL],
        environment: ["development"],
      },
      action: "ALLOW",
    },
  ],
};

console.log("=== Warden Trust Propagation & QUARANTINE ===\n");

// ---- Step 1: Agent reads content from the web ----
console.log("Step 1: Agent reads content from the web (EXTERNAL trust)\n");

const trustRegistry = new TrustRegistry();
const ledger = new MemoryLedgerStore();

// Simulate a read from the web — tagged EXTERNAL
const externalData = "This content came from the internet and could be malicious.";
const taggedExternal = tagValue(externalData, "web_scrape", "task-demo");
trustRegistry.register(externalData, TrustLevel.EXTERNAL, "web_scrape");

console.log(`  read_file from web → trust=${taggedExternal.trust} (EXTERNAL)`);
console.log(`  Value registered in TrustRegistry\n`);

// ---- Step 2: Agent tries to write that external content ----
console.log("Step 2: Agent tries to write_file with EXTERNAL content\n");

const writeInput = {
  path: "/tmp/output.txt",
  content: externalData,
  safeHeader: "Generated by Warden demo",
};

// Check what's in the trust registry
const lookupResult = trustRegistry.lookup(writeInput.content);
console.log(`  TrustRegistry.lookup("${externalData.slice(0, 40)}...") → ${lookupResult} (EXTERNAL)\n`);

// Evaluate — should trigger QUARANTINE
const decision = evaluate(config, {
  toolName: "write_file",
  toolInput: writeInput as Record<string, unknown>,
  environment: config.meta.environment,
  trustSources: [
    { source: "agent", trust: TrustLevel.AGENT },
    { source: "trust-registry", trust: TrustLevel.EXTERNAL },
  ],
  serverInAllowlist: true,
});

console.log(`  Policy decision: ${decision.action}`);
console.log(`  Reason: ${decision.reason}\n`);

// ---- Step 3: Strip EXTERNAL content, allow sanitized call ----
console.log("Step 3: Strip EXTERNAL values and allow sanitized call\n");

const { sanitized, stripped } = sanitizeExternalValues(writeInput, trustRegistry);

console.log(`  Stripped keys: [${stripped.join(", ") || "none"}]`);
console.log(`  Sanitized input:`, sanitized);

// Write quarantine event to ledger
const entry = {
  id: `quarantine_${Date.now()}`,
  previousHash: ledger.lastHash(),
  timestamp: new Date().toISOString(),
  sessionId: "session-demo",
  taskId: "task-demo",
  tool: "write_file",
  toolInput: sanitized,
  trustLevel: TrustLevel.EXTERNAL,
  trustSource: "web_scrape",
  policyRulesMatched: [decision.reason],
  decision: "QUARANTINE",
  decisionReason: decision.reason,
  hash: "",
  previousEntryHash: ledger.lastHash(),
};
ledger.write(entry);

console.log(`\n  Ledger chain valid: ${ledger.verifyChain().valid}`);
console.log(`  Quarantine event logged. Sanitized call proceeds.`);
